rs6000: Fix an error message in sysv4.h
While looking at PR82411, I got the error message

	error: '-msdata=-mcall' and 'eabi-linux' are incompatible

which caused some head-scratching.


	* config/rs6000/sysv4.h (SUBTARGET_OVERRIDE_OPTIONS): Correct error
	message for incompatible -msdata=* and -mcall-* options.


git-svn-id: svn://gcc.gnu.org/svn/gcc/trunk@253467 138bc75d-0d04-0410-961f-82ee72b054a4